### ISSUE TITLE
Not working correctly with asset pipeline

### ISSUE THREAD

**Issue by FreeApophis** [robin850/nivo-rails#6]
While it works perfectly in developer mode, the assets are missing in production.

* Of course I did a assets:precompile

After a quick look into the vendor assets it is clear that it does not use: asset_path therefore it won't work with the asset pipeline at least in Rails 4 and 5.

**Comment by robin850** [comment]
Hi @FreeApophis,

Sorry for being so long to post something here. Actually this should've been fixed with https://github.com/robin850/nivo-rails/pull/2 but it isn't part of any release. Could you check by referencing the GitHub repository in your Gemfile like this please:

~~~ruby
gem 'nivo-rails', github: 'robin850/nivo-rails'
~~~

If it's been fixed then I can issue a new release of this gem ! :-)

**Comment by FreeApophis** [comment]
Thanks for coming back to this, it indeed fixes the asset problem.

But you need to define a theme now.

Just for documentation reasons:
I have problems with the light and dark theme though, the arrows are only visible in combination with the theme-bar class. Could be a problem with my css or the dark and light theme are only meant to be used with the theme-bar (however they seemed positioned correclty, the arrows are just not visible.

Minimal example is now:

```ruby
    <%= nivo_slider class: "theme-default" do %>
```

**Comment by robin850** [comment]
Thank you very much @FreeApophis ! ❤️ 1.0.0 has been pushed to RubyGems.
